// =====================================================
// FILE: src/lib/pitboss/telemetry-coach.ts
// =====================================================

/**
 * PitBoss — Telemetry Analysis & Coach Engine
 * ----------------------------------------------
 * Post-session analysis over TelemetrySession data (from getTelemetrySession
 * in lib/telemetry.ts). Produces structured coaching insights covering:
 *   1. Lap comparison (delta-over-distance, sector deltas)
 *   2. Corner detection, braking/throttle technique per corner
 *   2b. Straight detection (the gaps between corners) — top speed, throttle
 *       discipline, DRS usage, and time delta vs a reference lap
 *   3. Consistency & mistake detection (lockups, snap corrections)
 *   4. Coaching narrative — summaryText, a note + a short suggestion for
 *      each corner AND each straight, plus top-level suggestions, are
 *      generated by the PitBoss LLM (pbInfer, mode 'reasoning') from the
 *      structured output of 1-3 above. The detection/analysis math itself
 *      stays fully deterministic — the LLM only writes the prose that
 *      interprets those numbers, it never invents the numbers.
 *   5. Track sanity check — cross-references the detected corner count
 *      against F1_TRACKS' known turn count for this circuit, and appends
 *      a caveat to the summary if detection looks substantially
 *      incomplete (see "Track sanity check" section below).
 *   6. Frame-density gate — a lap whose telemetry capture is too sparse
 *      (see MIN_FRAMES_PER_SECOND below) can't support any of the above
 *      trustworthily. Detected up front and short-circuits to an explicit
 *      "too sparse to analyze" report instead of silently running corner
 *      detection / comparison / narrative generation over data with
 *      multi-second blackouts in it.
 *
 * SERVER-ONLY: this file calls pbInfer, which reads PITBOSS_INTERNAL_KEY.
 * Never import this from a 'use client' component — see the recharts /
 * supabase-server bundling incident in TelemetryDashboard.tsx for why that
 * class of mistake is easy to make and hard to spot until deploy. Call
 * buildCoachingReport from a Server Component or Route Handler and pass
 * the resulting CoachingReport down as props/JSON instead.
 *
 * KNOWN GAP — track limits detection: TelemetryFrame.surfaceType exists
 * (see lib/telemetry-types.ts) but is optional and currently always
 * undefined in practice — the upstream aggregator that builds
 * raw_payload.telemetry doesn't copy CarTelemetryData.surfaceType through
 * yet (see the comment in lib/telemetry.ts's reshapeFrame). Without it,
 * "went off track" can only be inferred indirectly (e.g. a lap flagged
 * !lapValid), not pinpointed to a specific corner.
 *
 * KNOWN GAP — car-class redline lookup (see REDLINE_RPM_BY_CLASS below):
 * the field name/values for a session's car class haven't been confirmed
 * against the live TelemetrySession type, so the lookup currently reads
 * off an `any`-cast property. Verify and replace once confirmed.
 */

import { pbInfer } from '@/lib/pitboss-llm';
import { createAdminClient } from '@/lib/supabase/server';
import type { TelemetryFrame, TelemetryLap, TelemetrySession } from '@/lib/telemetry-types';

// Re-exported so existing server-side imports of these types from
// "@/lib/pitboss/telemetry-coach" keep working unchanged. Client components
// (e.g. CoachingPanel.tsx) should import from
// "@/lib/pitboss/telemetry-coach-types" directly instead, to avoid pulling
// this pbInfer-dependent module (and its secret key) into the client bundle.
export type {
  DeltaPoint,
  LapComparison,
  CornerSegment,
  BrakingAnalysis,
  ThrottleAnalysis,
  IssueKind,
  DetectedIssue,
  CornerCoaching,
  StraightSegment,
  StraightAnalysis,
  StraightCoaching,
  CoachingReport,
} from '@/lib/pitboss/telemetry-coach-types';

import type {
  DeltaPoint,
  LapComparison,
  CornerSegment,
  BrakingAnalysis,
  ThrottleAnalysis,
  DetectedIssue,
  CornerCoaching,
  StraightSegment,
  StraightAnalysis,
  StraightCoaching,
  CoachingReport,
} from '@/lib/pitboss/telemetry-coach-types';

export type SpeedUnit = 'kph' | 'mph';

// =======================================================================
// Speed unit conversion — all raw telemetry (frame.speed, F1 UDP's
// m_speed field) and all internal detection thresholds (MIN_APEX_SPEED_
// DROP_KMH, redline RPM lookups, etc.) are km/h always. Conversion to mph
// happens exactly once, at the buildCoachingReport boundary, only on
// values that get returned/displayed — never inside the detection math
// itself. See CoachingReport.speedUnit's doc comment for the contract.
// =======================================================================

const KPH_TO_MPH = 1 / 1.609344;

function convertSpeed(kph: number, unit: SpeedUnit): number {
  return unit === 'mph' ? kph * KPH_TO_MPH : kph;
}

function speedUnitLabel(unit: SpeedUnit): string {
  return unit === 'mph' ? 'mph' : 'km/h';
}

// =======================================================================
// Distance-domain resampling — the backbone of lap comparison. Frames
// arrive at fixed time intervals, not fixed distance intervals, so two
// laps rarely share sample points. Resample both onto a common distance
// grid before comparing.
// =======================================================================

// A grid point interpolated across a large real-time gap between the two
// bracketing frames (e.g. a dropped-UDP-packet capture dropout) is not a
// trustworthy value — see DeltaPoint.deltaSeconds in
// telemetry-coach-types.ts, which documents exactly this contract.
// Confirmed against real uploads: capture gaps are bursty (tight clusters
// of 16-50ms frames interrupted by multi-second blackouts), not a uniform
// downsample, so this has to be measured per-point, not assumed constant.
const SOURCE_GAP_UNRELIABLE_SECONDS = 0.5;

interface ResampledSpeedPoint {
  speed: number;
  /**
   * Estimated real-world time gap (seconds) between the two actual
   * telemetry frames bracketing this grid point, derived from their
   * distance gap and average speed. Large values mean this point was
   * linearly interpolated across a real capture gap, not measured.
   */
  sourceGapSeconds: number;
}

function resampleOntoGrid(frames: TelemetryFrame[], grid: number[]): ResampledSpeedPoint[] {
  // Linear-interpolates speed (raw km/h, straight from the F1 UDP
  // m_speed field) at each grid distance. Frames assumed sorted by dist
  // ascending.
  const result: ResampledSpeedPoint[] = [];
  let i = 0;
  for (const d of grid) {
    while (i < frames.length - 2 && frames[i + 1].dist < d) i++;
    const a = frames[i];
    const b = frames[Math.min(i + 1, frames.length - 1)];
    if (b.dist === a.dist) {
      result.push({ speed: a.speed, sourceGapSeconds: 0 });
      continue;
    }
    const t = (d - a.dist) / (b.dist - a.dist);
    const speed = a.speed + t * (b.speed - a.speed);
    // Convert km/h -> m/s before using speed to turn a distance gap
    // between the two real bracketing frames into a time-gap estimate.
    const avgSpeedMs = (a.speed + b.speed) / 2 / 3.6;
    const sourceGapSeconds = avgSpeedMs > 0.1 ? (b.dist - a.dist) / avgSpeedMs : 0;
    result.push({ speed, sourceGapSeconds });
  }
  return result;
}

function buildDistanceGrid(frames: TelemetryFrame[], stepMeters = 2): number[] {
  const maxDist = frames[frames.length - 1]?.dist ?? 0;
  const grid: number[] = [];
  for (let d = 0; d <= maxDist; d += stepMeters) grid.push(d);
  return grid;
}

/**
 * Converts a speed trace over a distance grid into cumulative time at
 * each grid point (time = distance / speed, integrated). Speed of 0
 * is clamped to a small epsilon to avoid division by zero (shouldn't
 * happen mid-lap, but stationary/pit-in frames could produce it).
 */
function speedTraceToCumulativeTime(speeds: number[], stepMeters: number): number[] {
  const EPSILON = 0.5; // m/s floor
  const cumulative: number[] = [0];
  for (let i = 1; i < speeds.length; i++) {
    // speeds[] is raw km/h (frame.speed, straight from F1 UDP's m_speed
    // field) — must convert to m/s before dividing distance by it.
    // Missing this made every dt, and therefore every deltaCurve point,
    // zone, and per-straight delta downstream, too small by ~3.6x.
    const avgSpeedMs = Math.max((speeds[i - 1] + speeds[i]) / 2 / 3.6, EPSILON);
    const dt = stepMeters / avgSpeedMs;
    cumulative.push(cumulative[i - 1] + dt);
  }
  return cumulative;
}

// =======================================================================
// 1. Lap comparison
// =======================================================================

export function compareLaps(lapA: TelemetryLap, lapB: TelemetryLap, stepMeters = 2): LapComparison {
  // getTelemetrySession() can legitimately produce a lap with zero frames
  // (payload?.telemetry ?? [] in lib/telemetry.ts). Without this guard,
  // resampleOntoGrid's frames[0] access throws an unhandled TypeError
  // instead of a message that tells the caller which lap is the problem.
  if (lapA.frames.length === 0 || lapB.frames.length === 0) {
    const badLap = lapA.frames.length === 0 ? lapA.lapNum : lapB.lapNum;
    throw new Error(`Cannot compare laps: lap ${badLap} has no telemetry frames.`);
  }

  const grid = buildDistanceGrid(
    lapA.frames.length > lapB.frames.length ? lapA.frames : lapB.frames,
    stepMeters
  );

  const resampledA = resampleOntoGrid(lapA.frames, grid);
  const resampledB = resampleOntoGrid(lapB.frames, grid);

  const timeA = speedTraceToCumulativeTime(resampledA.map((p) => p.speed), stepMeters);
  const timeB = speedTraceToCumulativeTime(resampledB.map((p) => p.speed), stepMeters);

  const deltaCurve: DeltaPoint[] = grid.map((dist, i) => {
    // If either lap's value at this grid point was interpolated across a
    // real capture gap, the delta here isn't measured data — it's a
    // straight line drawn through an unknown braking/apex/exit sequence.
    // Null it out rather than presenting invented smoothness as fact.
    const unreliable =
      resampledA[i].sourceGapSeconds > SOURCE_GAP_UNRELIABLE_SECONDS ||
      resampledB[i].sourceGapSeconds > SOURCE_GAP_UNRELIABLE_SECONDS;
    return {
      dist,
      deltaSeconds: unreliable ? null : timeB[i] - timeA[i],
    };
  });

  const totalDeltaSeconds = lapB.lapTime - lapA.lapTime;

  let biggestGainZone: LapComparison['biggestGainZone'] = null;
  let biggestLossZone: LapComparison['biggestLossZone'] = null;
  let minDelta = 0;
  let maxDelta = 0;
  let minIdx = 0;
  let maxIdx = 0;

  for (let i = 0; i < deltaCurve.length; i++) {
    const delta = deltaCurve[i].deltaSeconds;
    if (delta === null) continue;
    if (delta < minDelta) {
      minDelta = delta;
      minIdx = i;
    }
    if (delta > maxDelta) {
      maxDelta = delta;
      maxIdx = i;
    }
  }

  if (minDelta < -0.05) {
    // lapB gained time relative to lapA up to this point — find where the
    // gaining streak started by walking backward while delta keeps
    // improving. Stops at the first null boundary too, since we can't
    // compare across an unreliable point.
    let start = minIdx;
    while (
      start > 0 &&
      deltaCurve[start - 1].deltaSeconds !== null &&
      deltaCurve[start].deltaSeconds !== null &&
      (deltaCurve[start - 1].deltaSeconds as number) >= (deltaCurve[start].deltaSeconds as number)
    ) {
      start--;
    }
    biggestGainZone = {
      startDist: deltaCurve[start].dist,
      endDist: deltaCurve[minIdx].dist,
      gainedSeconds: Math.abs(minDelta),
    };
  }

  if (maxDelta > 0.05) {
    let start = maxIdx;
    while (
      start > 0 &&
      deltaCurve[start - 1].deltaSeconds !== null &&
      deltaCurve[start].deltaSeconds !== null &&
      (deltaCurve[start - 1].deltaSeconds as number) <= (deltaCurve[start].deltaSeconds as number)
    ) {
      start--;
    }
    biggestLossZone = {
      startDist: deltaCurve[start].dist,
      endDist: deltaCurve[maxIdx].dist,
      lostSeconds: maxDelta,
    };
  }

  return {
    lapA: lapA.lapNum,
    lapB: lapB.lapNum,
    deltaCurve,
    totalDeltaSeconds,
    sectorDeltas: {
      sector1: lapB.sector1 - lapA.sector1,
      sector2: lapB.sector2 - lapA.sector2,
      sector3: lapB.sector3 - lapA.sector3,
    },
    biggestGainZone,
    biggestLossZone,
  };
}

// =======================================================================
// 2. Corner detection — steering angle + lateral g threshold, with a
// consecutive-frame debounce, a gap-bridging pass, and an apex speed-drop
// sanity check.
//
// FIXED (Aug 2026, round 1): the original single-frame-threshold version
// misread flat-out straights as corners — curb/road-surface noise on a
// straight could spike gForceLateral over the old 0.3g threshold for one
// frame. Fixed by raising thresholds substantially and requiring several
// consecutive turning frames before treating anything as a corner entry.
//
// FIXED (Aug 2026, round 2): that fix then swallowed real corners — a
// Jeddah lap 4 complex hairpin/chicane at 480-640m (steering to -153°,
// lateral g to 2.97g, min speed 77 km/h) went completely undetected.
// Cause: the driver briefly straightens the wheel for ~8 frames between
// the two apexes of a double-apex corner. The old code treated that gap
// as "corner ended", splitting one real corner into fragments — and each
// fragment's own boundary frame was still mid-corner (slow), so the apex
// speed-drop sanity check compared the apex against a deceptively slow
// "exit" and rejected the whole thing as noise, along with every other
// multi-apex corner on the lap.
//
// Fix: (1) bridge separate turning runs into one corner when the gap
// between them is short (GAP_BRIDGE_METERS) — a brief straightening mid-
// corner shouldn't end the corner; (2) validate the apex speed drop
// against the car's true entry/exit speed — the fastest it was going in
// the REFERENCE_WINDOW_METERS immediately before/after the whole (possibly
// bridged) corner — rather than the corner segment's own boundary frame,
// which can still be mid-corner if bridging occurred.
//
// All speeds in this section (STEER_THRESHOLD_DEG excepted — that's
// degrees, not speed) are km/h always, regardless of the report's
// requested speedUnit — this is detection math, not a display value.
// =======================================================================

const STEER_THRESHOLD_DEG = 15; // realistic minimum steering input for an actual corner
const GLAT_THRESHOLD = 1.2; // g — filters out straight-line curb/road noise
const MIN_CONSECUTIVE_TURN_FRAMES = 4; // one noisy frame shouldn't start a corner
const MIN_APEX_SPEED_DROP_KMH = 15; // apex must be genuinely slower than true entry/exit, or it's not a corner — always km/h, independent of report display unit
const GAP_BRIDGE_METERS = 25; // bridge brief straightening within a complex corner (chicanes, hairpin doubles) so one real corner isn't fragmented
const REFERENCE_WINDOW_METERS = 150; // how far to look before/after a corner for its true (straight-line) entry/exit speed

function maxSpeedInWindow(
  frames: TelemetryFrame[],
  centerDist: number,
  direction: 'before' | 'after',
  windowMeters: number,
  fallback: number
): number {
  const lo = direction === 'before' ? centerDist - windowMeters : centerDist;
  const hi = direction === 'before' ? centerDist : centerDist + windowMeters;
  let max = -Infinity;
  for (const f of frames) {
    if (f.dist >= lo && f.dist <= hi) max = Math.max(max, f.speed);
  }
  return Number.isFinite(max) ? max : fallback;
}

export function detectCorners(frames: TelemetryFrame[]): CornerSegment[] {
  const corners: CornerSegment[] = [];
  const isTurning = frames.map(
    (f) => Math.abs(f.steer) > STEER_THRESHOLD_DEG || Math.abs(f.gLat) > GLAT_THRESHOLD
  );

  // Step 1: raw runs of consecutive turning frames (end is exclusive).
  const rawRuns: { start: number; end: number }[] = [];
  let i = 0;
  while (i < frames.length) {
    if (!isTurning[i]) {
      i++;
      continue;
    }
    let end = i;
    while (end < frames.length && isTurning[end]) end++;
    rawRuns.push({ start: i, end });
    i = end;
  }

  // Step 2: bridge runs separated by a short non-turning gap in distance —
  // see header comment for why this matters for double-apex corners.
  const mergedRuns: { start: number; end: number }[] = [];
  for (const run of rawRuns) {
    const last = mergedRuns[mergedRuns.length - 1];
    if (last && frames[run.start].dist - frames[last.end - 1].dist <= GAP_BRIDGE_METERS) {
      last.end = run.end;
    } else {
      mergedRuns.push({ ...run });
    }
  }

  let cornerId = 0;
  for (const run of mergedRuns) {
    const runLength = run.end - run.start;
    if (runLength < MIN_CONSECUTIVE_TURN_FRAMES) continue;

    const segment = frames.slice(run.start, run.end);

    // apex = point of minimum speed within the (possibly bridged) segment
    let apexIdx = 0;
    let minSpeed = Infinity;
    for (let j = 0; j < segment.length; j++) {
      if (segment[j].speed < minSpeed) {
        minSpeed = segment[j].speed;
        apexIdx = j;
      }
    }

    // Sanity check: compare the apex against the car's true entry/exit
    // speed — the fastest it was going in the window immediately before
    // and after this corner — not the segment's own boundary frame, which
    // can still be mid-corner (slow) if this corner was bridged from
    // multiple turning runs.
    const entrySpeed = segment[0].speed;
    const exitSpeed = segment[segment.length - 1].speed;
    const entryRef = maxSpeedInWindow(frames, frames[run.start].dist, 'before', REFERENCE_WINDOW_METERS, entrySpeed);
    const exitRef = maxSpeedInWindow(frames, frames[run.end - 1].dist, 'after', REFERENCE_WINDOW_METERS, exitSpeed);
    const referenceSpeed = Math.min(entryRef, exitRef);
    if (referenceSpeed - minSpeed < MIN_APEX_SPEED_DROP_KMH) {
      continue;
    }

    const avgSteer = segment.reduce((sum, f) => sum + f.steer, 0) / segment.length;

    corners.push({
      id: cornerId++,
      entryDist: frames[run.start].dist,
      apexDist: segment[apexIdx].dist,
      exitDist: frames[run.end - 1].dist,
      direction: avgSteer < 0 ? 'left' : 'right', // sign convention depends on game's steer field — verify against a known left-hander
    });
  }

  return corners;
}

// =======================================================================
// 2b. Straight detection — the gaps between corners (and before the first
// / after the last corner) are the straights. Kept simple: no separate
// thresholding, just the complement of the corner list along the lap.
// Very short gaps between corners (e.g. two corners in quick succession
// that didn't get bridged by detectCorners' GAP_BRIDGE_METERS) aren't
// worth surfacing as their own "straight" — there's nothing to coach in a
// 20m connecting kerb.
// =======================================================================

const MIN_STRAIGHT_METERS = 50;

export function detectStraights(frames: TelemetryFrame[], corners: CornerSegment[]): StraightSegment[] {
  const lapEnd = frames[frames.length - 1]?.dist ?? 0;
  const straights: StraightSegment[] = [];
  let straightId = 0;

  let cursor = 0;
  let afterCornerId: number | null = null;

  for (const corner of corners) {
    if (corner.entryDist - cursor >= MIN_STRAIGHT_METERS) {
      straights.push({
        id: straightId++,
        startDist: cursor,
        endDist: corner.entryDist,
        afterCornerId,
        beforeCornerId: corner.id,
      });
    }
    cursor = corner.exitDist;
    afterCornerId = corner.id;
  }

  if (lapEnd - cursor >= MIN_STRAIGHT_METERS) {
    straights.push({
      id: straightId++,
      startDist: cursor,
      endDist: lapEnd,
      afterCornerId,
      beforeCornerId: null,
    });
  }

  return straights;
}

function framesInRange(frames: TelemetryFrame[], startDist: number, endDist: number): TelemetryFrame[] {
  return frames.filter((f) => f.dist >= startDist && f.dist <= endDist);
}

// Resolves a raw F1 UDP track name (e.g. "Sakhir", "Abu Dhabi", "Austin")
// to its canonical name + nominal turn count, for the track sanity check
// below. Deliberately reuses pitboss.f1_track_name_aliases — the same
// alias table telemetry-ingest already relies on to resolve track_id for
// setup submissions — rather than a second, separate name-matching
// heuristic. An earlier version of this check used a static in-memory
// table (lib/pitboss/f1-tracks.ts) with its own ad-hoc substring matcher;
// that silently failed for "Sakhir" (confirmed against real uploaded
// laps) and would have also failed for "abu dhabi", "austin"/"cota",
// "montreal", "interlagos"/"sao paulo", "red bull ring", "losail",
// "catalunya", "mexico city", "hungaroring", "saudi arabia", "yas
// marina" — roughly half of the real name variants the game actually
// sends — because its id scheme (country-based: 'melbourne', 'austria',
// 'mexico', 'usa') doesn't line up with pitboss.tracks' slug scheme
// (circuit-based: 'albert-park', 'red-bull-ring', 'mexico-city', 'cota').
// Rather than maintain a third mapping to reconcile the two, this reads
// straight from the one place turn counts now live: pitboss.tracks.turns
// (added specifically for this check — see its column comment).
async function getTrackTurnsForRawName(rawName: string): Promise<{ name: string; turns: number } | null> {
  const needle = rawName.trim().toLowerCase();
  if (!needle) return null;

  const supabase = createAdminClient();
  const { data: alias } = await supabase
    .schema('pitboss')
    .from('f1_track_name_aliases')
    .select('track_id')
    .eq('game_track_name', needle)
    .maybeSingle();
  if (!alias) return null;

  const { data: track } = await supabase
    .schema('pitboss')
    .from('tracks')
    .select('name, turns')
    .eq('id', alias.track_id)
    .maybeSingle();
  if (!track || track.turns == null) return null;

  return { name: track.name, turns: track.turns };
}

export function analyzeStraight(
  frames: TelemetryFrame[],
  straight: StraightSegment,
  comparison: LapComparison | null
): StraightAnalysis {
  const zone = framesInRange(frames, straight.startDist, straight.endDist);

  // topSpeed is always km/h at this stage — converted to the report's
  // requested speedUnit once, at the buildCoachingReport boundary.
  let topSpeed = 0;
  let topSpeedDist = straight.startDist;
  for (const f of zone) {
    if (f.speed > topSpeed) {
      topSpeed = f.speed;
      topSpeedDist = f.dist;
    }
  }

  const avgThrottle = zone.length > 0 ? zone.reduce((s, f) => s + f.throttle, 0) / zone.length : 0;
  const drsFrames = zone.filter((f) => f.drs);
  const drsActivePercent = zone.length > 0 ? drsFrames.length / zone.length : 0;

  // Time delta across this straight's distance range, sourced from the
  // already-computed lap comparison rather than recomputing anything —
  // consistent with the rule that the LLM (and this helper) never invents
  // numbers, only reads what compareLaps already produced. Skips any
  // deltaCurve point whose value is null (unreliable — see DeltaPoint) so
  // a single capture gap inside this straight's range doesn't silently
  // corrupt the delta; if the endpoints we need are unreliable, the
  // result is null rather than a wrong number.
  let deltaVsReferenceSeconds: number | null = null;
  if (comparison) {
    const inRange = comparison.deltaCurve.filter((p) => p.dist >= straight.startDist && p.dist <= straight.endDist);
    if (inRange.length >= 2) {
      const first = inRange[0].deltaSeconds;
      const last = inRange[inRange.length - 1].deltaSeconds;
      if (first !== null && last !== null) {
        deltaVsReferenceSeconds = last - first;
      }
    }
  }

  return {
    straightId: straight.id,
    lengthMeters: straight.endDist - straight.startDist,
    topSpeed,
    topSpeedDist,
    avgThrottle,
    drsActivePercent,
    deltaVsReferenceSeconds,
  };
}

// =======================================================================
// 3. Braking analysis per corner
// =======================================================================

const BRAKE_THRESHOLD = 0.1; // 0-1 scale
const THROTTLE_THRESHOLD = 0.1;
const FULL_THROTTLE_THRESHOLD = 0.95;

export function analyzeBraking(
  frames: TelemetryFrame[],
  corner: CornerSegment,
  previousCorner: CornerSegment | null
): BrakingAnalysis {
  // Look slightly before corner entry for the actual brake point, which
  // usually precedes the steering input. Clamped to the previous corner's
  // exit so a close-together sequence — the same case GAP_BRIDGE_METERS
  // exists to handle for detection (chicanes, tight corner sequences) —
  // doesn't pull braking/trail-brake frames that actually belong to the
  // prior corner into this one's analysis. Without the clamp, a fixed
  // 150m lookback can extend past the previous corner's exit whenever two
  // corners sit closer together than 150m.
  const searchStart = previousCorner
    ? Math.max(corner.entryDist - 150, previousCorner.exitDist)
    : Math.max(0, corner.entryDist - 150);
  const zone = framesInRange(frames, searchStart, corner.apexDist);

  const brakingFrames = zone.filter((f) => f.brake > BRAKE_THRESHOLD);
  const brakePointDist = brakingFrames[0]?.dist ?? corner.entryDist;
  const brakePeakPressure = brakingFrames.reduce((max, f) => Math.max(max, f.brake), 0);
  const brakeDurationMeters =
    brakingFrames.length > 0
      ? brakingFrames[brakingFrames.length - 1].dist - brakingFrames[0].dist
      : 0;

  const trailBrakeFrames = brakingFrames.filter((f) => Math.abs(f.steer) > STEER_THRESHOLD_DEG);
  const trailBrakePercent = brakingFrames.length > 0 ? trailBrakeFrames.length / brakingFrames.length : 0;

  const cornerFrames = framesInRange(frames, corner.entryDist, corner.exitDist);
  const minSpeedInCorner = cornerFrames.reduce((min, f) => Math.min(min, f.speed), Infinity);

  return {
    cornerId: corner.id,
    brakePointDist,
    brakePeakPressure,
    brakeDurationMeters,
    trailBrakePercent,
    // Always km/h at this stage — converted to the report's requested
    // speedUnit once, at the buildCoachingReport boundary.
    minSpeedInCorner: Number.isFinite(minSpeedInCorner) ? minSpeedInCorner : 0,
  };
}

// =======================================================================
// 4. Throttle analysis per corner
// =======================================================================

export function analyzeThrottle(frames: TelemetryFrame[], corner: CornerSegment, nextCorner: CornerSegment | null): ThrottleAnalysis {
  const searchEnd = nextCorner ? nextCorner.entryDist : corner.exitDist + 300;
  const zone = framesInRange(frames, corner.apexDist, searchEnd);

  const throttleFrames = zone.filter((f) => f.throttle > THROTTLE_THRESHOLD);
  const throttleApplicationDist = throttleFrames[0]?.dist ?? corner.apexDist;
  const distFromApexToThrottle = throttleApplicationDist - corner.apexDist;

  const fullThrottleFrame = zone.find((f) => f.throttle >= FULL_THROTTLE_THRESHOLD);
  const fullThrottleDist = fullThrottleFrame?.dist ?? null;

  // Smoothness: lower variance in frame-to-frame throttle delta = smoother
  // ramp, not a jabby/inconsistent application.
  const rampFrames = zone.filter((f) => f.dist <= (fullThrottleDist ?? searchEnd));
  let smoothness = 1;
  if (rampFrames.length > 2) {
    const deltas: number[] = [];
    for (let i = 1; i < rampFrames.length; i++) deltas.push(rampFrames[i].throttle - rampFrames[i - 1].throttle);
    const mean = deltas.reduce((s, d) => s + d, 0) / deltas.length;
    const variance = deltas.reduce((s, d) => s + (d - mean) ** 2, 0) / deltas.length;
    smoothness = Math.max(0, 1 - variance * 20); // scaled heuristic, not a calibrated physical unit
  }

  return {
    cornerId: corner.id,
    throttleApplicationDist,
    distFromApexToThrottle,
    fullThrottleDist,
    applicationSmoothness: smoothness,
  };
}

// =======================================================================
// 5. Consistency & mistake detection
// =======================================================================

// Redline thresholds by car class. SetupGen/telemetry-coach covers
// multiple F1 car classes, and a single fixed RPM ceiling misfires
// (false positives or missed detections) for any class whose rev limit
// differs from whichever car 11500 was originally tuned against.
//
// KNOWN GAP: the key strings here (and the field read off session/lap to
// look one up — see getRedlineRpm's caller in buildCoachingReport) have
// not been confirmed against the live car-class data actually available
// on TelemetrySession/TelemetryLap. Treat this as a best-effort lookup
// with a safe default, not a verified mapping — confirm the real field
// name and class values, then replace the `as any` cast at the call site.
const REDLINE_RPM_BY_CLASS: Record<string, number> = {
  f1: 11500,
  f2: 11500,
};
const DEFAULT_REDLINE_RPM = 11500;

function getRedlineRpm(carClass: string | null | undefined): number {
  if (!carClass) return DEFAULT_REDLINE_RPM;
  return REDLINE_RPM_BY_CLASS[carClass.toLowerCase()] ?? DEFAULT_REDLINE_RPM;
}

// =======================================================================
// FIXED (2026-09): ISSUE_MERGE_DIST_METERS (a flat 3m distance threshold)
// merged same-kind issues that were close together in DISTANCE. But
// issues are emitted once per FRAME, and frame-to-frame distance scales
// with speed (and with capture rate, which this same file documents
// elsewhere as bursty/variable — see SOURCE_GAP_UNRELIABLE_SECONDS's
// comment). At typical corner-exit/straight-line speeds, consecutive
// frames are commonly 5-8m apart — already past the old 3m threshold —
// so a single sustained over-rev or sustained snap-correction run failed
// to merge and was reported as N separate issues, one per frame, exactly
// the failure this mechanism exists to prevent (see DetectedIssue.endDist's
// doc comment). Confirmed against real uploads: a single continuous
// over-rev run produced 15-16 separate "Held N RPM" issues in one corner,
// all a few meters apart but past the 3m cutoff.
//
// FIX: merge by FRAME ADJACENCY instead of raw distance. Frame adjacency
// is invariant to speed and capture-rate variance — "the last frame that
// produced a same-kind issue was N frames ago" is a stable signal in a
// way that "was N meters ago" is not. Merging now happens inline in
// detectIssues (via the local `emit` helper below) rather than as a
// separate post-pass, since it needs the frame index, which isn't part
// of DetectedIssue's public shape and was never meant to be exposed there.
// =======================================================================

// Consecutive same-kind issues within this many FRAMES (not meters) of
// each other are one sustained condition, not N separate events. A small
// frame-index gap (2) tolerates one skipped/filtered frame without
// breaking the merge, same as the old distance threshold intended, but
// doesn't depend on speed or capture rate.
const ISSUE_MERGE_FRAME_GAP = 2;

export function detectIssues(
  frames: TelemetryFrame[],
  redlineRpm: number = DEFAULT_REDLINE_RPM,
  speedUnit: SpeedUnit = 'kph'
): DetectedIssue[] {
  const issues: DetectedIssue[] = [];
  const unitLabel = speedUnitLabel(speedUnit);

  // Tracks, per issue kind, the frame index at which that kind was last
  // emitted/extended and the index into `issues` of that entry — so a new
  // detection can extend the existing entry (bump endDist, escalate
  // severity) instead of always pushing a new one.
  const lastFrameIndexByKind = new Map<DetectedIssue['kind'], number>();
  const lastIssueIndexByKind = new Map<DetectedIssue['kind'], number>();

  function emit(kind: DetectedIssue['kind'], frameIdx: number, dist: number, severity: 'minor' | 'major', note: string) {
    const lastFrameIdx = lastFrameIndexByKind.get(kind);
    const lastIssueIdx = lastIssueIndexByKind.get(kind);
    if (
      lastFrameIdx !== undefined &&
      lastIssueIdx !== undefined &&
      frameIdx - lastFrameIdx <= ISSUE_MERGE_FRAME_GAP
    ) {
      // Extend the existing sustained-condition entry rather than
      // starting a new one.
      const existing = issues[lastIssueIdx];
      existing.endDist = dist;
      if (severity === 'major') existing.severity = 'major';
    } else {
      issues.push({ kind, dist, severity, note });
      lastIssueIndexByKind.set(kind, issues.length - 1);
    }
    lastFrameIndexByKind.set(kind, frameIdx);
  }

  for (let i = 2; i < frames.length; i++) {
    const prev = frames[i - 1];
    const curr = frames[i];

    // Lockup heuristic: heavy braking + longitudinal g suddenly collapses
    // (locked tyres generate less stopping force than a rolling tyre at
    // the grip limit) while speed keeps dropping. Not a direct wheel-lock
    // signal — F1 UDP doesn't expose per-wheel slip ratio — so this is a
    // proxy, not a certainty. Validate against a known locked-wheel replay
    // before trusting severity labels.
    if (curr.brake > 0.8 && prev.brake > 0.8) {
      const gDrop = prev.gLon - curr.gLon; // gLon expected negative under braking; a sudden move toward 0 = grip loss
      if (gDrop > 0.4 && curr.speed < prev.speed) {
        emit(
          'lockup',
          i,
          curr.dist,
          gDrop > 0.7 ? 'major' : 'minor',
          `Possible lockup — braking g dropped ${gDrop.toFixed(2)}g while still on the brakes.`
        );
      }
    }

    // Snap correction: large, fast steering reversal at speed — proxy for
    // a near-spin or correction after losing the rear. Threshold is a
    // starting guess. curr.speed (km/h internally) is converted + labeled
    // here since this note text is user-facing and now needs to match
    // whatever unit the rest of the report is displayed in.
    const steerDelta = curr.steer - prev.steer;
    if (Math.abs(steerDelta) > 25 && curr.speed > 30 && Math.sign(steerDelta) !== Math.sign(prev.steer - frames[i - 2].steer)) {
      const displaySpeed = convertSpeed(curr.speed, speedUnit);
      emit(
        'snap_correction',
        i,
        curr.dist,
        Math.abs(steerDelta) > 45 ? 'major' : 'minor',
        `Sharp steering correction (${steerDelta.toFixed(0)}° in one frame) at ${displaySpeed.toFixed(0)} ${unitLabel} — possible rear-end slide.`
      );
    }

    // Over-rev: sustained RPM at/above redline without a gear change
    // suggests a missed upshift, not a deliberate hold. redlineRpm is
    // caller-supplied (see getRedlineRpm) so this doesn't misfire for car
    // classes with a different rev limit than the original 11500 tuning.
    if (curr.rpm > 0 && prev.gear === curr.gear && curr.rpm > 0.98 * (prev.rpm || curr.rpm) && curr.rpm > redlineRpm) {
      emit(
        'engine_over_rev',
        i,
        curr.dist,
        'minor',
        `Held ${curr.rpm} RPM in gear ${curr.gear} — check for a missed upshift.`
      );
    }
  }

  return issues;
}

// =======================================================================
// 6. Coaching narrative — LLM-generated summaryText, a note + a short
// suggestion for each corner AND each straight, plus top-level
// suggestions, all built from the structured output of sections 1-5
// above. The LLM never sees raw frame data, only the already-computed
// numbers, so it can't invent facts that contradict the deterministic
// analysis.
// =======================================================================

interface NarrativeCornerInput {
  id: number;
  direction: 'left' | 'right';
  entryDist: number;
  apexDist: number;
  exitDist: number;
  brakePointDist: number;
  brakePeakPressure: number;
  brakeDurationMeters: number;
  trailBrakePercent: number;
  minSpeedInCorner: number; // already in the report's requested speedUnit
  throttleApplicationDist: number;
  distFromApexToThrottle: number;
  fullThrottleDist: number | null;
  applicationSmoothness: number;
  issues: DetectedIssue[];
}

interface NarrativeStraightInput {
  id: number;
  startDist: number;
  endDist: number;
  lengthMeters: number;
  topSpeed: number; // already in the report's requested speedUnit
  topSpeedDist: number;
  avgThrottle: number;
  drsActivePercent: number;
  deltaVsReferenceSeconds: number | null;
}

interface NarrativeInput {
  lapNum: number;
  lapTime: number;
  lapValid: boolean;
  referenceLapNum: number | null;
  speedUnit: SpeedUnit;
  comparison: {
    totalDeltaSeconds: number;
    sectorDeltas: { sector1: number; sector2: number; sector3: number };
    biggestGainZone: LapComparison['biggestGainZone'];
    biggestLossZone: LapComparison['biggestLossZone'];
  } | null;
  corners: NarrativeCornerInput[];
  straights: NarrativeStraightInput[];
  generalIssues: DetectedIssue[];
}

interface CoachingNarrative {
  summaryText: string;
  cornerNotes: Map<number, string>;
  cornerSuggestions: Map<number, string>;
  straightNotes: Map<number, string>;
  straightSuggestions: Map<number, string>;
  suggestions: string[];
  source: 'llm' | 'deterministic';
}

// Builds the system prompt with the correct speed-unit instruction baked
// in. Previously this was a static string hardcoding "speeds in km/h" —
// with speedUnit now selectable per-report, a hardcoded unit label would
// have the LLM writing "km/h" in its prose right next to mph numbers.
function buildCoachSystemPrompt(speedUnit: SpeedUnit): string {
  const unitLabel = speedUnitLabel(speedUnit);
  return `You are PitBoss's sim-racing driving coach for F1 UDP telemetry.
You are given the ALREADY-COMPUTED structured output of a deterministic telemetry analysis for one lap: lap time, an optional comparison against a reference lap, a per-corner breakdown (braking point/pressure/duration, trail-brake %, min corner speed, throttle application point, distance from apex to throttle, full-throttle point, throttle smoothness 0-1, and any detected issues), and a per-straight breakdown (length, top speed and where it was reached, average throttle 0-1, % of the straight with DRS active, and time delta vs the reference lap across that straight if available).

Your job is ONLY to interpret these numbers in plain, encouraging but honest coaching language. Do not invent facts, distances, or times that are not present in the data. Do not contradict the numbers given. If a value is missing or looks like a sensor gap (e.g. fullThrottleDist is null), say so rather than guessing.

Corner numbering: each corner object has an "id" field starting at 0 — this is an internal array index, NOT the display number. Always refer to corners using id+1 in your prose (e.g. id 0 is "Corner 1", id 2 is "Corner 3"), to match what the driver sees on screen. Never write "corner 0" or any other 0-indexed reference. Straights should be referred to descriptively (e.g. "the straight after Corner 3") rather than by a straight id number, since the driver doesn't see straight numbers on screen.

Field names are internal variable names, not driving vocabulary — describe what they mean in plain racing language instead of naming the field. For example, say "throttle came on a bit late after the apex" rather than "distFromApexToThrottle was high".

Units: distances in meters, speeds in ${unitLabel} (all speed values given — topSpeed, minSpeedInCorner — are already converted to this unit; use it consistently in your prose), times in seconds, angles in degrees, pressures/smoothness/throttle on a 0-1 scale.

Respond with ONLY a single JSON object, no markdown fences, no prose outside the JSON, matching exactly this shape:
{
  "summary": "2-4 sentence overall lap summary",
  "cornerNotes": { "<cornerId>": "1-3 sentence coaching note for that corner", ... one entry per corner id given ... },
  "cornerSuggestions": { "<cornerId>": "1 short, concrete, single-focus next-lap tip for that corner — the ONE thing to try differently, or a short affirmation if execution was clean", ... one entry per corner id given ... },
  "straightNotes": { "<straightId>": "1-2 sentence note about that straight — top speed reached, throttle discipline, DRS usage, and/or time delta if given", ... one entry per straight id given ... },
  "straightSuggestions": { "<straightId>": "1 short, concrete tip for that straight, or a short affirmation if it was clean", ... one entry per straight id given ... },
  "suggestions": ["3-5 short, concrete, prioritized next-lap tips covering the whole lap, each grounded in a specific number, corner, or straight from the data above, described in plain racing language rather than field names. Order from highest-impact first. Do not repeat the summary verbatim."]
}`;
}

function stripJsonFences(text: string): string {
  return text.replace(/```json|```/g, '').trim();
}

// Recovers a JSON object embedded in surrounding prose. Added because the
// 'reasoning' mode model (routed through pitboss-proxy) frequently returns
// its entire chain-of-thought as plain text before the actual JSON answer
// — e.g. "We need to produce JSON with summary, cornerNotes... Corner 0:
// direction right..." followed eventually by the real { ... } object. Some
// OpenRouter free-tier providers for reasoning models don't separate the
// reasoning trace into its own response field, so this can't be fixed by
// reading a different field — the reasoning text is mixed into the same
// string as the answer. Rather than require the whole response to be pure
// JSON (which was silently discarding a correct answer buried in prose and
// falling back to the deterministic narrative on nearly every call),
// find the last balanced {...} block by scanning backward from the final
// '}' and tracking brace depth, and parse just that substring.
function extractTrailingJsonObject(text: string): string | null {
  const lastBrace = text.lastIndexOf('}');
  if (lastBrace === -1) return null;
  let depth = 0;
  for (let i = lastBrace; i >= 0; i--) {
    if (text[i] === '}') depth++;
    else if (text[i] === '{') {
      depth--;
      if (depth === 0) return text.slice(i, lastBrace + 1);
    }
  }
  return null;
}

interface ParsedNarrative {
  summary: string;
  cornerNotes: Record<string, string>;
  cornerSuggestions: Record<string, string>;
  straightNotes: Record<string, string>;
  straightSuggestions: Record<string, string>;
  suggestions: string[];
}

function isStringRecord(v: unknown): v is Record<string, string> {
  return !!v && typeof v === 'object' && !Array.isArray(v) && Object.values(v).every((x) => typeof x === 'string');
}

function isValidParsedNarrative(parsed: any): parsed is ParsedNarrative {
  return !!(
    parsed &&
    typeof parsed.summary === 'string' &&
    isStringRecord(parsed.cornerNotes) &&
    isStringRecord(parsed.cornerSuggestions) &&
    isStringRecord(parsed.straightNotes) &&
    isStringRecord(parsed.straightSuggestions) &&
    Array.isArray(parsed.suggestions) &&
    parsed.suggestions.every((s: unknown) => typeof s === 'string')
  );
}

// Accepts `unknown` rather than `string` deliberately — result.response is
// typed as `string` in InferResult, but that's just a TypeScript `as` cast
// on pbInfer's end (see pitboss-llm.ts's workerPost — the worker's JSON is
// trusted blindly, no runtime validation), not an actual runtime
// guarantee. Confirmed in production: the worker/upstream provider has
// returned `response: null` at least once (crashing this function's old
// `raw.replace(...)` with an unguarded TypeError), and separately returned
// a plain-text safety-classifier string ("User Safety: safe") instead of
// real completion content. Both were only "caught" by accident, via the
// outer try/catch around the whole pbInfer call in
// generateCoachingNarrative — this makes the guard explicit and local
// instead of relying on that.
function parseNarrativeResponse(raw: unknown): ParsedNarrative | null {
  if (typeof raw !== 'string' || raw.trim().length === 0) return null;

  const cleaned = stripJsonFences(raw);

  // Fast path: a well-behaved model returned pure JSON with nothing else.
  try {
    const parsed = JSON.parse(cleaned);
    if (isValidParsedNarrative(parsed)) return parsed;
  } catch {
    // fall through to extraction below
  }

  // Slow path: recover the JSON object from inside a reasoning trace. See
  // extractTrailingJsonObject's comment for why this is needed.
  const extracted = extractTrailingJsonObject(cleaned);
  if (extracted) {
    try {
      const parsed = JSON.parse(extracted);
      if (isValidParsedNarrative(parsed)) return parsed;
    } catch {
      return null;
    }
  }

  return null;
}

/**
 * Deterministic suggestions builder — ranks the most actionable findings
 * from the structured analysis into 3-5 concrete top-level tips. Used both
 * as the fallback when the LLM call fails/is unparseable, and as a sanity
 * reference the LLM path never needs but this keeps the two code paths
 * symmetric with buildDeterministicNarrative below.
 */
function buildDeterministicSuggestions(input: NarrativeInput): string[] {
  const suggestions: string[] = [];

  if (input.comparison?.biggestLossZone) {
    const z = input.comparison.biggestLossZone;
    suggestions.push(
      `Focus here first: ${z.lostSeconds.toFixed(2)}s lost between ${z.startDist.toFixed(0)}m and ${z.endDist.toFixed(0)}m vs lap ${input.referenceLapNum}.`
    );
  }

  const brakedCorners = input.corners.filter((c) => c.brakeDurationMeters > 0);
  if (brakedCorners.length > 0) {
    const worstTrail = brakedCorners.reduce((a, b) => (a.trailBrakePercent < b.trailBrakePercent ? a : b));
    if (worstTrail.trailBrakePercent < 0.3) {
      suggestions.push(
        `Corner ${worstTrail.id + 1}: only ${(worstTrail.trailBrakePercent * 100).toFixed(0)}% trail brake — carry a bit more brake into the turn to rotate the car earlier.`
      );
    }
  }

  if (input.corners.length > 0) {
    const roughest = input.corners.reduce((a, b) => (a.applicationSmoothness < b.applicationSmoothness ? a : b));
    if (roughest.applicationSmoothness < 0.5) {
      suggestions.push(
        `Corner ${roughest.id + 1}: throttle application is inconsistent on exit — smooth the initial squeeze before going to full throttle.`
      );
    }

    const latestThrottle = input.corners.reduce((a, b) => (a.distFromApexToThrottle > b.distFromApexToThrottle ? a : b));
    if (latestThrottle.distFromApexToThrottle > 20) {
      suggestions.push(
        `Corner ${latestThrottle.id + 1}: throttle came on ${latestThrottle.distFromApexToThrottle.toFixed(0)}m after the apex — there may be time available getting back to power sooner.`
      );
    }
  }

  const liftingStraight = input.straights.find((s) => s.avgThrottle < 0.9);
  if (liftingStraight) {
    suggestions.push(
      `Throttle wasn't fully pinned on the ${liftingStraight.lengthMeters.toFixed(0)}m straight around ${liftingStraight.startDist.toFixed(0)}m — check for an unnecessary lift.`
    );
  }

  const majorIssues = input.generalIssues.filter((i) => i.severity === 'major');
  if (majorIssues.length > 0) {
    const kinds = new Set(majorIssues.map((i) => i.kind));
    if (kinds.has('lockup')) {
      suggestions.push(`Lockup events detected this lap — ease initial brake pressure to avoid flat-spotting the tyres.`);
    }
    if (kinds.has('snap_correction')) {
      suggestions.push(`The rear stepped out at least once — consider slightly less aggressive turn-in or throttle mid-corner.`);
    }
    if (kinds.has('engine_over_rev')) {
      suggestions.push(`At least one missed upshift this lap — check your shift points, you're bouncing off the limiter.`);
    }
  }

  return suggestions.slice(0, 5);
}

function deterministicCornerSuggestion(c: NarrativeCornerInput): string {
  const majorIssue = c.issues.find((iss) => iss.severity === 'major');
  if (majorIssue) {
    if (majorIssue.kind === 'lockup') return 'Ease initial brake pressure here to avoid the lockup.';
    if (majorIssue.kind === 'snap_correction') return 'A smoother initial input here should keep the rear settled.';
    if (majorIssue.kind === 'engine_over_rev') return 'Shift a touch earlier here to stop bouncing off the limiter.';
  }
  if (c.brakeDurationMeters > 0 && c.trailBrakePercent < 0.3) {
    return 'Carry a bit more brake into the corner to rotate the car earlier.';
  }
  if (c.applicationSmoothness < 0.5) {
    return 'Smooth out the throttle application on exit.';
  }
  if (c.distFromApexToThrottle > 20) {
    return 'Get back to power sooner after the apex.';
  }
  return 'Solid execution here — no clear time on the table.';
}

function deterministicStraightNote(s: NarrativeStraightInput, unitLabel: string): string {
  const parts: string[] = [];
  parts.push(`${s.lengthMeters.toFixed(0)}m straight, top speed ${s.topSpeed.toFixed(0)} ${unitLabel} at ${s.topSpeedDist.toFixed(0)}m.`);
  if (s.drsActivePercent > 0) {
    parts.push(`DRS active ${(s.drsActivePercent * 100).toFixed(0)}% of the way.`);
  }
  if (s.deltaVsReferenceSeconds != null) {
    const sign = s.deltaVsReferenceSeconds >= 0 ? '+' : '';
    parts.push(`${sign}${s.deltaVsReferenceSeconds.toFixed(3)}s vs the reference lap here.`);
  }
  return parts.join(' ');
}

function deterministicStraightSuggestion(s: NarrativeStraightInput): string {
  if (s.avgThrottle < 0.9) {
    return 'Throttle was not held fully flat the whole way — check for an unnecessary lift.';
  }
  if (s.deltaVsReferenceSeconds != null && s.deltaVsReferenceSeconds > 0.05) {
    return `Losing ${s.deltaVsReferenceSeconds.toFixed(2)}s here vs the reference lap — likely down to exit speed from the corner before it, not this straight itself.`;
  }
  return 'Full throttle held cleanly — nothing to change here.';
}

/**
 * Deterministic fallback narrative — used when the LLM call fails, times
 * out, or returns something we can't parse. Template-built from the same
 * structured input the LLM would have received, so the UI always gets a
 * usable summary, per-corner and per-straight notes/suggestions, and
 * top-level suggestions even if the PitBoss worker is down.
 */
function buildDeterministicNarrative(input: NarrativeInput): CoachingNarrative {
  const unitLabel = speedUnitLabel(input.speedUnit);
  const summaryParts: string[] = [];
  summaryParts.push(`Lap ${input.lapNum}: ${input.lapTime.toFixed(3)}s${input.lapValid ? '' : ' (invalid)'}.`);
  if (input.comparison) {
    const sign = input.comparison.totalDeltaSeconds >= 0 ? '+' : '';
    summaryParts.push(`${sign}${input.comparison.totalDeltaSeconds.toFixed(3)}s vs lap ${input.referenceLapNum}.`);
    if (input.comparison.biggestLossZone) {
      summaryParts.push(
        `Biggest loss: ${input.comparison.biggestLossZone.lostSeconds.toFixed(2)}s between ${input.comparison.biggestLossZone.startDist.toFixed(0)}m–${input.comparison.biggestLossZone.endDist.toFixed(0)}m.`
      );
    }
  }
  const majorIssueCount = input.generalIssues.filter((i) => i.severity === 'major').length;
  if (majorIssueCount > 0) {
    summaryParts.push(`${majorIssueCount} major issue(s) detected this lap.`);
  }

  const cornerNotes = new Map<number, string>();
  const cornerSuggestions = new Map<number, string>();
  for (const c of input.corners) {
    const parts: string[] = [];
    parts.push(`Braked at ${c.brakePointDist.toFixed(0)}m, peak ${(c.brakePeakPressure * 100).toFixed(0)}% brake pressure, min speed ${c.minSpeedInCorner.toFixed(0)} ${unitLabel}.`);
    parts.push(`Trail-braked through ${(c.trailBrakePercent * 100).toFixed(0)}% of the braking zone.`);
    parts.push(
      c.fullThrottleDist != null
        ? `Throttle applied ${c.distFromApexToThrottle.toFixed(0)}m after apex, full throttle by ${c.fullThrottleDist.toFixed(0)}m.`
        : `Throttle applied ${c.distFromApexToThrottle.toFixed(0)}m after apex; full throttle not reached before the next braking zone.`
    );
    if (c.issues.length > 0) {
      parts.push(`${c.issues.length} issue(s) flagged in this corner.`);
    }
    cornerNotes.set(c.id, parts.join(' '));
    cornerSuggestions.set(c.id, deterministicCornerSuggestion(c));
  }

  const straightNotes = new Map<number, string>();
  const straightSuggestions = new Map<number, string>();
  for (const s of input.straights) {
    straightNotes.set(s.id, deterministicStraightNote(s, unitLabel));
    straightSuggestions.set(s.id, deterministicStraightSuggestion(s));
  }

  return {
    summaryText: summaryParts.join(' '),
    cornerNotes,
    cornerSuggestions,
    straightNotes,
    straightSuggestions,
    suggestions: buildDeterministicSuggestions(input),
    source: 'deterministic',
  };
}

async function generateCoachingNarrative(input: NarrativeInput): Promise<CoachingNarrative> {
  try {
    const result = await pbInfer({
      mode: 'reasoning',
      system: buildCoachSystemPrompt(input.speedUnit),
      prompt: JSON.stringify(input),
      max_tokens: 2000,
      temperature: 0.4,
    });

    const parsed = parseNarrativeResponse(result.response);
    if (parsed) {
      const toMap = (rec: Record<string, string>) => {
        const m = new Map<number, string>();
        for (const [key, note] of Object.entries(rec)) {
          const id = Number(key);
          if (Number.isFinite(id)) m.set(id, note);
        }
        return m;
      };
      return {
        summaryText: parsed.summary,
        cornerNotes: toMap(parsed.cornerNotes),
        cornerSuggestions: toMap(parsed.cornerSuggestions),
        straightNotes: toMap(parsed.straightNotes),
        straightSuggestions: toMap(parsed.straightSuggestions),
        suggestions: parsed.suggestions,
        source: 'llm',
      };
    }

    console.error('[telemetry-coach] pbInfer returned unparseable narrative JSON, falling back to deterministic:', result.response);
  } catch (err) {
    console.error('[telemetry-coach] pbInfer call failed, falling back to deterministic narrative:', err);
  }
  return buildDeterministicNarrative(input);
}

// =======================================================================
// 7. Top-level orchestrator
// =======================================================================

// A lap whose telemetry capture is too sparse can't support corner
// detection, braking/throttle analysis, or lap comparison trustworthily —
// see the Aug 2026 investigation: a 350-frame, 101.44s lap (3.45 frames/
// sec) against a healthy ~16.5 frames/sec baseline produced a straight
// line through what should have been an entire braking-apex-exit
// sequence, and only detected 4 of a track's ~16 corners. Gated up front
// so a lap like this returns an explicit "too sparse to analyze" report
// instead of silently running the full pipeline over fabricated zones.
const MIN_FRAMES_PER_SECOND = 8;

function buildSparseDataReport(
  lapNum: number,
  referenceLapNum: number | null,
  frameCount: number,
  lapTimeSeconds: number,
  speedUnit: SpeedUnit
): CoachingReport {
  const density = lapTimeSeconds > 0 ? frameCount / lapTimeSeconds : 0;
  return {
    lapNum,
    referenceLapNum,
    comparison: null,
    corners: [],
    straights: [],
    issues: [],
    summaryText: `Lap ${lapNum}: telemetry capture for this lap is too sparse to analyze reliably (${frameCount} frames over ${lapTimeSeconds.toFixed(1)}s, ~${density.toFixed(1)} frames/sec — below the ${MIN_FRAMES_PER_SECOND}/sec floor needed to trust corner detection and lap comparison). This is likely dropped UDP packets during capture, not a real driving event. No corner, straight, or comparison analysis was run for this lap.`,
    suggestions: [],
    narrativeSource: 'deterministic',
    speedUnit,
  };
}

export async function buildCoachingReport(
  session: TelemetrySession,
  lapNum: number,
  referenceLapNum?: number,
  speedUnit: SpeedUnit = 'kph'
): Promise<CoachingReport> {
  const lap = session.laps.find((l) => l.lapNum === lapNum);
  if (!lap) throw new Error(`Lap ${lapNum} not found in session ${session.sessionUid}`);

  // Frame-density gate — see MIN_FRAMES_PER_SECOND comment above. Checked
  // before any detection/comparison/LLM work runs, on the primary lap
  // being analyzed (not the reference lap — a sparse reference lap still
  // degrades comparison quality but doesn't invalidate this lap's own
  // corner/straight/issue analysis the way sparse data on THIS lap does).
  if (lap.lapTime > 0 && lap.frames.length / lap.lapTime < MIN_FRAMES_PER_SECOND) {
    return buildSparseDataReport(lapNum, referenceLapNum ?? null, lap.frames.length, lap.lapTime, speedUnit);
  }

  const referenceLap = referenceLapNum != null ? session.laps.find((l) => l.lapNum === referenceLapNum) : undefined;
  const comparison = referenceLap ? compareLaps(referenceLap, lap) : null;

  // KNOWN GAP: car class field/values unconfirmed against the live
  // TelemetrySession type — see REDLINE_RPM_BY_CLASS's header comment.
  const redlineRpm = getRedlineRpm((session as any).carClass ?? (lap as any).carClass);

  const corners = detectCorners(lap.frames);
  const cornerAnalysis = corners.map((corner, idx) => {
    const braking = analyzeBraking(lap.frames, corner, corners[idx - 1] ?? null);
    const throttle = analyzeThrottle(lap.frames, corner, corners[idx + 1] ?? null);
    const cornerIssues = detectIssues(framesInRange(lap.frames, corner.entryDist - 50, corner.exitDist + 50), redlineRpm, speedUnit);
    return { corner, braking, throttle, issues: cornerIssues };
  });

  const straights = detectStraights(lap.frames, corners);
  const straightAnalysis = straights.map((straight) => ({
    straight,
    analysis: analyzeStraight(lap.frames, straight, comparison),
  }));

  const allIssues = detectIssues(lap.frames, redlineRpm, speedUnit);

  const narrativeInput: NarrativeInput = {
    lapNum: lap.lapNum,
    lapTime: lap.lapTime,
    lapValid: lap.lapValid,
    referenceLapNum: referenceLapNum ?? null,
    speedUnit,
    comparison: comparison
      ? {
          totalDeltaSeconds: comparison.totalDeltaSeconds,
          sectorDeltas: comparison.sectorDeltas,
          biggestGainZone: comparison.biggestGainZone,
          biggestLossZone: comparison.biggestLossZone,
        }
      : null,
    corners: cornerAnalysis.map(({ corner, braking, throttle, issues }) => ({
      id: corner.id,
      direction: corner.direction,
      entryDist: corner.entryDist,
      apexDist: corner.apexDist,
      exitDist: corner.exitDist,
      brakePointDist: braking.brakePointDist,
      brakePeakPressure: braking.brakePeakPressure,
      brakeDurationMeters: braking.brakeDurationMeters,
      trailBrakePercent: braking.trailBrakePercent,
      minSpeedInCorner: convertSpeed(braking.minSpeedInCorner, speedUnit),
      throttleApplicationDist: throttle.throttleApplicationDist,
      distFromApexToThrottle: throttle.distFromApexToThrottle,
      fullThrottleDist: throttle.fullThrottleDist,
      applicationSmoothness: throttle.applicationSmoothness,
      issues,
    })),
    straights: straightAnalysis.map(({ straight, analysis }) => ({
      id: straight.id,
      startDist: straight.startDist,
      endDist: straight.endDist,
      lengthMeters: analysis.lengthMeters,
      topSpeed: convertSpeed(analysis.topSpeed, speedUnit),
      topSpeedDist: analysis.topSpeedDist,
      avgThrottle: analysis.avgThrottle,
      drsActivePercent: analysis.drsActivePercent,
      deltaVsReferenceSeconds: analysis.deltaVsReferenceSeconds,
    })),
    generalIssues: allIssues,
  };

  const narrative = await generateCoachingNarrative(narrativeInput);

  // Only computed if the LLM (or its fallback) left a gap — e.g. the model
  // omitted a corner or straight despite being given all of them.
  let deterministicFallback: CoachingNarrative | null = null;
  const fallback = (): CoachingNarrative => {
    if (!deterministicFallback) deterministicFallback = buildDeterministicNarrative(narrativeInput);
    return deterministicFallback;
  };

  // Final output objects carry display-unit speeds (converted once here),
  // matching narrativeInput above and CoachingReport.speedUnit's contract
  // — braking/analysis themselves stay km/h-internal and are never
  // mutated; these are fresh copies.
  const corners_: CornerCoaching[] = cornerAnalysis.map(({ corner, braking, throttle, issues }) => ({
    corner,
    braking: { ...braking, minSpeedInCorner: convertSpeed(braking.minSpeedInCorner, speedUnit) },
    throttle,
    issues,
    coachingNote: narrative.cornerNotes.get(corner.id) ?? fallback().cornerNotes.get(corner.id) ?? '',
    suggestion: narrative.cornerSuggestions.get(corner.id) ?? fallback().cornerSuggestions.get(corner.id) ?? '',
  }));

  const straights_: StraightCoaching[] = straightAnalysis.map(({ straight, analysis }) => ({
    straight,
    analysis: { ...analysis, topSpeed: convertSpeed(analysis.topSpeed, speedUnit) },
    coachingNote: narrative.straightNotes.get(straight.id) ?? fallback().straightNotes.get(straight.id) ?? '',
    suggestion: narrative.straightSuggestions.get(straight.id) ?? fallback().straightSuggestions.get(straight.id) ?? '',
  }));

  // Track sanity check — cross-reference detected corner count against the
  // known turn count for this circuit (see lib/pitboss/f1-tracks.ts). If
  // detection looks substantially incomplete (fewer than half the real
  // corners found), append an explicit caveat rather than silently
  // presenting a partial lap as if it were the whole picture. This is a
  // deterministic, always-on check — it runs regardless of whether the
  // narrative came from the LLM or the fallback template.
  let summaryText = narrative.summaryText;
  const trackInfo = await getTrackTurnsForRawName(lap.track);
  if (trackInfo && trackInfo.turns > 0) {
    const detectedRatio = corners.length / trackInfo.turns;
    if (detectedRatio < 0.5) {
      summaryText += ` Note: only ${corners.length} of ${trackInfo.name}'s ~${trackInfo.turns} corners were detected this lap — some corners may be missing from this analysis.`;
    }
  }

  return {
    lapNum,
    referenceLapNum: referenceLapNum ?? null,
    comparison,
    corners: corners_,
    straights: straights_,
    issues: allIssues,
    summaryText,
    suggestions: narrative.suggestions,
    narrativeSource: narrative.source,
    speedUnit,
  };
}
