/**
 * PitBoss — Telemetry Analysis & Coach Engine
 * ----------------------------------------------
 * Post-session analysis over TelemetrySession data (from getTelemetrySession
 * in lib/telemetry.ts). Produces structured coaching insights covering:
 *   1. Lap comparison (delta-over-distance, sector deltas)
 *   2. Braking/throttle technique per corner
 *   3. Consistency & mistake detection (lockups, snap corrections)
 *   4. Coaching narrative — summaryText, each corner's coachingNote, and
 *      top-level suggestions are generated by the PitBoss LLM (pbInfer,
 *      mode 'reasoning') from the structured output of 1–3 above. The
 *      detection/analysis math itself (compareLaps, detectCorners,
 *      analyzeBraking, analyzeThrottle, detectIssues) stays fully
 *      deterministic — the LLM only writes the prose that interprets
 *      those numbers, it never invents the numbers.
 *
 * SERVER-ONLY: this file calls pbInfer, which reads PITBOSS_INTERNAL_KEY.
 * Never import this from a 'use client' component — see the recharts /
 * supabase-server bundling incident in TelemetryDashboard.tsx for why that
 * class of mistake is easy to make and hard to spot until deploy. Call
 * buildCoachingReport from a Server Component or Route Handler and pass
 * the resulting CoachingReport down as props/JSON instead.
 *
 * KNOWN GAP — track limits detection: TelemetryFrame.surfaceType exists
 * (see lib/telemetry-types.ts) but is optional and currently always
 * undefined in practice — the upstream aggregator that builds
 * raw_payload.telemetry doesn't copy CarTelemetryData.surfaceType through
 * yet (see the comment in lib/telemetry.ts's reshapeFrame). Without it,
 * "went off track" can only be inferred indirectly (e.g. a lap flagged
 * !lapValid), not pinpointed to a specific corner.
 */

import { pbInfer } from '@/lib/pitboss-llm';
import type { TelemetryFrame, TelemetryLap, TelemetrySession } from '@/lib/telemetry-types';

// Re-exported so existing server-side imports of these types from
// "@/lib/pitboss/telemetry-coach" keep working unchanged. Client components
// (e.g. CoachingPanel.tsx) should import from
// "@/lib/pitboss/telemetry-coach-types" directly instead, to avoid pulling
// this pbInfer-dependent module (and its secret key) into the client bundle.
export type {
  DeltaPoint,
  LapComparison,
  CornerSegment,
  BrakingAnalysis,
  ThrottleAnalysis,
  IssueKind,
  DetectedIssue,
  CornerCoaching,
  CoachingReport,
} from '@/lib/pitboss/telemetry-coach-types';

import type {
  DeltaPoint,
  LapComparison,
  CornerSegment,
  BrakingAnalysis,
  ThrottleAnalysis,
  DetectedIssue,
  CornerCoaching,
  CoachingReport,
} from '@/lib/pitboss/telemetry-coach-types';

// =======================================================================
// Distance-domain resampling — the backbone of lap comparison. Frames
// arrive at fixed time intervals, not fixed distance intervals, so two
// laps rarely share sample points. Resample both onto a common distance
// grid before comparing.
// =======================================================================

function resampleOntoGrid(frames: TelemetryFrame[], grid: number[]): number[] {
  // Linear-interpolates speed (m/s equivalent, whatever unit frames use)
  // at each grid distance. Frames assumed sorted by dist ascending.
  const result: number[] = [];
  let i = 0;
  for (const d of grid) {
    while (i < frames.length - 2 && frames[i + 1].dist < d) i++;
    const a = frames[i];
    const b = frames[Math.min(i + 1, frames.length - 1)];
    if (b.dist === a.dist) {
      result.push(a.speed);
      continue;
    }
    const t = (d - a.dist) / (b.dist - a.dist);
    result.push(a.speed + t * (b.speed - a.speed));
  }
  return result;
}

function buildDistanceGrid(frames: TelemetryFrame[], stepMeters = 2): number[] {
  const maxDist = frames[frames.length - 1]?.dist ?? 0;
  const grid: number[] = [];
  for (let d = 0; d <= maxDist; d += stepMeters) grid.push(d);
  return grid;
}

/**
 * Converts a speed trace over a distance grid into cumulative time at
 * each grid point (time = distance / speed, integrated). Speed of 0
 * is clamped to a small epsilon to avoid division by zero (shouldn't
 * happen mid-lap, but stationary/pit-in frames could produce it).
 */
function speedTraceToCumulativeTime(speeds: number[], stepMeters: number): number[] {
  const EPSILON = 0.5; // m/s floor
  const cumulative: number[] = [0];
  for (let i = 1; i < speeds.length; i++) {
    const avgSpeed = Math.max((speeds[i - 1] + speeds[i]) / 2, EPSILON);
    const dt = stepMeters / avgSpeed;
    cumulative.push(cumulative[i - 1] + dt);
  }
  return cumulative;
}

// =======================================================================
// 1. Lap comparison
// =======================================================================

export function compareLaps(lapA: TelemetryLap, lapB: TelemetryLap, stepMeters = 2): LapComparison {
  // getTelemetrySession() can legitimately produce a lap with zero frames
  // (payload?.telemetry ?? [] in lib/telemetry.ts). Without this guard,
  // resampleOntoGrid's frames[0] access throws an unhandled TypeError
  // instead of a message that tells the caller which lap is the problem.
  if (lapA.frames.length === 0 || lapB.frames.length === 0) {
    const badLap = lapA.frames.length === 0 ? lapA.lapNum : lapB.lapNum;
    throw new Error(`Cannot compare laps: lap ${badLap} has no telemetry frames.`);
  }

  const grid = buildDistanceGrid(
    lapA.frames.length > lapB.frames.length ? lapA.frames : lapB.frames,
    stepMeters
  );

  const speedsA = resampleOntoGrid(lapA.frames, grid);
  const speedsB = resampleOntoGrid(lapB.frames, grid);

  const timeA = speedTraceToCumulativeTime(speedsA, stepMeters);
  const timeB = speedTraceToCumulativeTime(speedsB, stepMeters);

  const deltaCurve: DeltaPoint[] = grid.map((dist, i) => ({
    dist,
    deltaSeconds: timeB[i] - timeA[i],
  }));

  const totalDeltaSeconds = lapB.lapTime - lapA.lapTime;

  let biggestGainZone: LapComparison['biggestGainZone'] = null;
  let biggestLossZone: LapComparison['biggestLossZone'] = null;
  let minDelta = 0;
  let maxDelta = 0;
  let minIdx = 0;
  let maxIdx = 0;

  for (let i = 0; i < deltaCurve.length; i++) {
    if (deltaCurve[i].deltaSeconds < minDelta) {
      minDelta = deltaCurve[i].deltaSeconds;
      minIdx = i;
    }
    if (deltaCurve[i].deltaSeconds > maxDelta) {
      maxDelta = deltaCurve[i].deltaSeconds;
      maxIdx = i;
    }
  }

  if (minDelta < -0.05) {
    // lapB gained time relative to lapA up to this point — find where the
    // gaining streak started by walking backward while delta keeps improving
    let start = minIdx;
    while (start > 0 && deltaCurve[start - 1].deltaSeconds >= deltaCurve[start].deltaSeconds) start--;
    biggestGainZone = {
      startDist: deltaCurve[start].dist,
      endDist: deltaCurve[minIdx].dist,
      gainedSeconds: Math.abs(minDelta),
    };
  }

  if (maxDelta > 0.05) {
    let start = maxIdx;
    while (start > 0 && deltaCurve[start - 1].deltaSeconds <= deltaCurve[start].deltaSeconds) start--;
    biggestLossZone = {
      startDist: deltaCurve[start].dist,
      endDist: deltaCurve[maxIdx].dist,
      lostSeconds: maxDelta,
    };
  }

  return {
    lapA: lapA.lapNum,
    lapB: lapB.lapNum,
    deltaCurve,
    totalDeltaSeconds,
    sectorDeltas: {
      sector1: lapB.sector1 - lapA.sector1,
      sector2: lapB.sector2 - lapA.sector2,
      sector3: lapB.sector3 - lapA.sector3,
    },
    biggestGainZone,
    biggestLossZone,
  };
}

// =======================================================================
// 2. Corner detection — steering angle + lateral g threshold, with a
// consecutive-frame debounce, a gap-bridging pass, and an apex speed-drop
// sanity check.
//
// FIXED (Aug 2026, round 1): the original single-frame-threshold version
// misread flat-out straights as corners — curb/road-surface noise on a
// straight could spike gForceLateral over the old 0.3g threshold for one
// frame. Fixed by raising thresholds substantially and requiring several
// consecutive turning frames before treating anything as a corner entry.
//
// FIXED (Aug 2026, round 2): that fix then swallowed real corners — a
// Jeddah lap 4 complex hairpin/chicane at 480-640m (steering to -153°,
// lateral g to 2.97g, min speed 77 km/h) went completely undetected.
// Cause: the driver briefly straightens the wheel for ~8 frames between
// the two apexes of a double-apex corner. The old code treated that gap
// as "corner ended", splitting one real corner into fragments — and each
// fragment's own boundary frame was still mid-corner (slow), so the apex
// speed-drop sanity check compared the apex against a deceptively slow
// "exit" and rejected the whole thing as noise, along with every other
// multi-apex corner on the lap.
//
// Fix: (1) bridge separate turning runs into one corner when the gap
// between them is short (GAP_BRIDGE_METERS) — a brief straightening mid-
// corner shouldn't end the corner; (2) validate the apex speed drop
// against the car's true entry/exit speed — the fastest it was going in
// the REFERENCE_WINDOW_METERS immediately before/after the whole (possibly
// bridged) corner — rather than the corner segment's own boundary frame,
// which can still be mid-corner if bridging occurred.
// =======================================================================

const STEER_THRESHOLD_DEG = 15; // realistic minimum steering input for an actual corner
const GLAT_THRESHOLD = 1.2; // g — filters out straight-line curb/road noise
const MIN_CONSECUTIVE_TURN_FRAMES = 4; // one noisy frame shouldn't start a corner
const MIN_APEX_SPEED_DROP_KMH = 15; // apex must be genuinely slower than true entry/exit, or it's not a corner
const GAP_BRIDGE_METERS = 25; // bridge brief straightening within a complex corner (chicanes, hairpin doubles) so one real corner isn't fragmented
const REFERENCE_WINDOW_METERS = 150; // how far to look before/after a corner for its true (straight-line) entry/exit speed

function maxSpeedInWindow(
  frames: TelemetryFrame[],
  centerDist: number,
  direction: 'before' | 'after',
  windowMeters: number,
  fallback: number
): number {
  const lo = direction === 'before' ? centerDist - windowMeters : centerDist;
  const hi = direction === 'before' ? centerDist : centerDist + windowMeters;
  let max = -Infinity;
  for (const f of frames) {
    if (f.dist >= lo && f.dist <= hi) max = Math.max(max, f.speed);
  }
  return Number.isFinite(max) ? max : fallback;
}

export function detectCorners(frames: TelemetryFrame[]): CornerSegment[] {
  const corners: CornerSegment[] = [];
  const isTurning = frames.map(
    (f) => Math.abs(f.steer) > STEER_THRESHOLD_DEG || Math.abs(f.gLat) > GLAT_THRESHOLD
  );

  // Step 1: raw runs of consecutive turning frames (end is exclusive).
  const rawRuns: { start: number; end: number }[] = [];
  let i = 0;
  while (i < frames.length) {
    if (!isTurning[i]) {
      i++;
      continue;
    }
    let end = i;
    while (end < frames.length && isTurning[end]) end++;
    rawRuns.push({ start: i, end });
    i = end;
  }

  // Step 2: bridge runs separated by a short non-turning gap in distance —
  // see header comment for why this matters for double-apex corners.
  const mergedRuns: { start: number; end: number }[] = [];
  for (const run of rawRuns) {
    const last = mergedRuns[mergedRuns.length - 1];
    if (last && frames[run.start].dist - frames[last.end - 1].dist <= GAP_BRIDGE_METERS) {
      last.end = run.end;
    } else {
      mergedRuns.push({ ...run });
    }
  }

  let cornerId = 0;
  for (const run of mergedRuns) {
    const runLength = run.end - run.start;
    if (runLength < MIN_CONSECUTIVE_TURN_FRAMES) continue;

    const segment = frames.slice(run.start, run.end);

    // apex = point of minimum speed within the (possibly bridged) segment
    let apexIdx = 0;
    let minSpeed = Infinity;
    for (let j = 0; j < segment.length; j++) {
      if (segment[j].speed < minSpeed) {
        minSpeed = segment[j].speed;
        apexIdx = j;
      }
    }

    // Sanity check: compare the apex against the car's true entry/exit
    // speed — the fastest it was going in the window immediately before
    // and after this corner — not the segment's own boundary frame, which
    // can still be mid-corner (slow) if this corner was bridged from
    // multiple turning runs.
    const entrySpeed = segment[0].speed;
    const exitSpeed = segment[segment.length - 1].speed;
    const entryRef = maxSpeedInWindow(frames, frames[run.start].dist, 'before', REFERENCE_WINDOW_METERS, entrySpeed);
    const exitRef = maxSpeedInWindow(frames, frames[run.end - 1].dist, 'after', REFERENCE_WINDOW_METERS, exitSpeed);
    const referenceSpeed = Math.min(entryRef, exitRef);
    if (referenceSpeed - minSpeed < MIN_APEX_SPEED_DROP_KMH) {
      continue;
    }

    const avgSteer = segment.reduce((sum, f) => sum + f.steer, 0) / segment.length;

    corners.push({
      id: cornerId++,
      entryDist: frames[run.start].dist,
      apexDist: segment[apexIdx].dist,
      exitDist: frames[run.end - 1].dist,
      direction: avgSteer < 0 ? 'left' : 'right', // sign convention depends on game's steer field — verify against a known left-hander
    });
  }

  return corners;
}

// =======================================================================
// 3. Braking analysis per corner
// =======================================================================

const BRAKE_THRESHOLD = 0.1; // 0-1 scale
const THROTTLE_THRESHOLD = 0.1;
const FULL_THROTTLE_THRESHOLD = 0.95;

function framesInRange(frames: TelemetryFrame[], startDist: number, endDist: number): TelemetryFrame[] {
  return frames.filter((f) => f.dist >= startDist && f.dist <= endDist);
}

export function analyzeBraking(frames: TelemetryFrame[], corner: CornerSegment): BrakingAnalysis {
  // Look slightly before corner entry for the actual brake point, which
  // usually precedes the steering input.
  const searchStart = Math.max(0, corner.entryDist - 150);
  const zone = framesInRange(frames, searchStart, corner.apexDist);

  const brakingFrames = zone.filter((f) => f.brake > BRAKE_THRESHOLD);
  const brakePointDist = brakingFrames[0]?.dist ?? corner.entryDist;
  const brakePeakPressure = brakingFrames.reduce((max, f) => Math.max(max, f.brake), 0);
  const brakeDurationMeters =
    brakingFrames.length > 0
      ? brakingFrames[brakingFrames.length - 1].dist - brakingFrames[0].dist
      : 0;

  const trailBrakeFrames = brakingFrames.filter((f) => Math.abs(f.steer) > STEER_THRESHOLD_DEG);
  const trailBrakePercent = brakingFrames.length > 0 ? trailBrakeFrames.length / brakingFrames.length : 0;

  const cornerFrames = framesInRange(frames, corner.entryDist, corner.exitDist);
  const minSpeedInCorner = cornerFrames.reduce((min, f) => Math.min(min, f.speed), Infinity);

  return {
    cornerId: corner.id,
    brakePointDist,
    brakePeakPressure,
    brakeDurationMeters,
    trailBrakePercent,
    minSpeedInCorner: Number.isFinite(minSpeedInCorner) ? minSpeedInCorner : 0,
  };
}

// =======================================================================
// 4. Throttle analysis per corner
// =======================================================================

export function analyzeThrottle(frames: TelemetryFrame[], corner: CornerSegment, nextCorner: CornerSegment | null): ThrottleAnalysis {
  const searchEnd = nextCorner ? nextCorner.entryDist : corner.exitDist + 300;
  const zone = framesInRange(frames, corner.apexDist, searchEnd);

  const throttleFrames = zone.filter((f) => f.throttle > THROTTLE_THRESHOLD);
  const throttleApplicationDist = throttleFrames[0]?.dist ?? corner.apexDist;
  const distFromApexToThrottle = throttleApplicationDist - corner.apexDist;

  const fullThrottleFrame = zone.find((f) => f.throttle >= FULL_THROTTLE_THRESHOLD);
  const fullThrottleDist = fullThrottleFrame?.dist ?? null;

  // Smoothness: lower variance in frame-to-frame throttle delta = smoother
  // ramp, not a jabby/inconsistent application.
  const rampFrames = zone.filter((f) => f.dist <= (fullThrottleDist ?? searchEnd));
  let smoothness = 1;
  if (rampFrames.length > 2) {
    const deltas: number[] = [];
    for (let i = 1; i < rampFrames.length; i++) deltas.push(rampFrames[i].throttle - rampFrames[i - 1].throttle);
    const mean = deltas.reduce((s, d) => s + d, 0) / deltas.length;
    const variance = deltas.reduce((s, d) => s + (d - mean) ** 2, 0) / deltas.length;
    smoothness = Math.max(0, 1 - variance * 20); // scaled heuristic, not a calibrated physical unit
  }

  return {
    cornerId: corner.id,
    throttleApplicationDist,
    distFromApexToThrottle,
    fullThrottleDist,
    applicationSmoothness: smoothness,
  };
}

// =======================================================================
// 5. Consistency & mistake detection
// =======================================================================

export function detectIssues(frames: TelemetryFrame[]): DetectedIssue[] {
  const issues: DetectedIssue[] = [];

  for (let i = 2; i < frames.length; i++) {
    const prev = frames[i - 1];
    const curr = frames[i];

    // Lockup heuristic: heavy braking + longitudinal g suddenly collapses
    // (locked tyres generate less stopping force than a rolling tyre at
    // the grip limit) while speed keeps dropping. Not a direct wheel-lock
    // signal — F1 UDP doesn't expose per-wheel slip ratio — so this is a
    // proxy, not a certainty. Validate against a known locked-wheel replay
    // before trusting severity labels.
    if (curr.brake > 0.8 && prev.brake > 0.8) {
      const gDrop = prev.gLon - curr.gLon; // gLon expected negative under braking; a sudden move toward 0 = grip loss
      if (gDrop > 0.4 && curr.speed < prev.speed) {
        issues.push({
          kind: 'lockup',
          dist: curr.dist,
          severity: gDrop > 0.7 ? 'major' : 'minor',
          note: `Possible lockup — braking g dropped ${gDrop.toFixed(2)}g while still on the brakes.`,
        });
      }
    }

    // Snap correction: large, fast steering reversal at speed — proxy for
    // a near-spin or correction after losing the rear. Threshold is a
    // starting guess.
    const steerDelta = curr.steer - prev.steer;
    if (Math.abs(steerDelta) > 25 && curr.speed > 30 && Math.sign(steerDelta) !== Math.sign(prev.steer - frames[i - 2].steer)) {
      issues.push({
        kind: 'snap_correction',
        dist: curr.dist,
        severity: Math.abs(steerDelta) > 45 ? 'major' : 'minor',
        note: `Sharp steering correction (${steerDelta.toFixed(0)}° in one frame) at ${curr.speed.toFixed(0)} — possible rear-end slide.`,
      });
    }

    // Over-rev: sustained RPM at/above redline without a gear change
    // suggests a missed upshift, not a deliberate hold.
    if (curr.rpm > 0 && prev.gear === curr.gear && curr.rpm > 0.98 * (prev.rpm || curr.rpm) && curr.rpm > 11500) {
      issues.push({
        kind: 'engine_over_rev',
        dist: curr.dist,
        severity: 'minor',
        note: `Held ${curr.rpm} RPM in gear ${curr.gear} — check for a missed upshift.`,
      });
    }
  }

  return issues;
}

// =======================================================================
// 6. Coaching narrative — LLM-generated summaryText, per-corner
// coachingNote, and top-level suggestions, all built from the structured
// output of sections 1–5 above. The LLM never sees raw frame data, only
// the already-computed numbers, so it can't invent facts that contradict
// the deterministic analysis.
// =======================================================================

interface NarrativeCornerInput {
  id: number;
  direction: 'left' | 'right';
  entryDist: number;
  apexDist: number;
  exitDist: number;
  brakePointDist: number;
  brakePeakPressure: number;
  brakeDurationMeters: number;
  trailBrakePercent: number;
  minSpeedInCorner: number;
  throttleApplicationDist: number;
  distFromApexToThrottle: number;
  fullThrottleDist: number | null;
  applicationSmoothness: number;
  issues: DetectedIssue[];
}

interface NarrativeInput {
  lapNum: number;
  lapTime: number;
  lapValid: boolean;
  referenceLapNum: number | null;
  comparison: {
    totalDeltaSeconds: number;
    sectorDeltas: { sector1: number; sector2: number; sector3: number };
    biggestGainZone: LapComparison['biggestGainZone'];
    biggestLossZone: LapComparison['biggestLossZone'];
  } | null;
  corners: NarrativeCornerInput[];
  generalIssues: DetectedIssue[];
}

interface CoachingNarrative {
  summaryText: string;
  cornerNotes: Map<number, string>;
  suggestions: string[];
  source: 'llm' | 'deterministic';
}

const COACH_SYSTEM_PROMPT = `You are PitBoss's sim-racing driving coach for F1 UDP telemetry.
You are given the ALREADY-COMPUTED structured output of a deterministic telemetry analysis for one lap: lap time, an optional comparison against a reference lap, and a per-corner breakdown (braking point/pressure/duration, trail-brake %, min corner speed, throttle application point, distance from apex to throttle, full-throttle point, throttle smoothness 0-1, and any detected issues in that corner).

Your job is ONLY to interpret these numbers in plain, encouraging but honest coaching language. Do not invent facts, distances, or times that are not present in the data. Do not contradict the numbers given. If a value is missing or looks like a sensor gap (e.g. fullThrottleDist is null), say so rather than guessing.

Corner numbering: each corner object has an "id" field starting at 0 — this is an internal array index, NOT the display number. Always refer to corners using id+1 in your prose (e.g. id 0 is "Corner 1", id 2 is "Corner 3"), to match what the driver sees on screen. Never write "corner 0" or any other 0-indexed reference.

Field names are internal variable names, not driving vocabulary — describe what they mean in plain racing language instead of naming the field. For example, say "throttle came on a bit late after the apex" rather than "distFromApexToThrottle was high", and "the throttle ramp was inconsistent" rather than mentioning "applicationSmoothness" by name.

Units: distances in meters, speeds in km/h, times in seconds, angles in degrees, pressures/smoothness on a 0-1 scale.

Respond with ONLY a single JSON object, no markdown fences, no prose outside the JSON, matching exactly this shape:
{
  "summary": "2-4 sentence overall lap summary",
  "cornerNotes": { "<cornerId>": "1-3 sentence coaching note for that corner", ... one entry per corner id given ... },
  "suggestions": ["3-5 short, concrete, prioritized next-lap tips, each grounded in a specific number or corner from the data above — e.g. reference a corner by its display number (id+1), a distance, or a time delta, described in plain racing language rather than field names. Order from highest-impact first. Do not repeat the summary verbatim."]
}`;

function stripJsonFences(text: string): string {
  return text.replace(/```json|```/g, '').trim();
}

function parseNarrativeResponse(
  raw: string
): { summary: string; cornerNotes: Record<string, string>; suggestions: string[] } | null {
  try {
    const parsed = JSON.parse(stripJsonFences(raw));
    if (
      parsed &&
      typeof parsed.summary === 'string' &&
      parsed.cornerNotes &&
      typeof parsed.cornerNotes === 'object' &&
      !Array.isArray(parsed.cornerNotes) &&
      Array.isArray(parsed.suggestions) &&
      parsed.suggestions.every((s: unknown) => typeof s === 'string')
    ) {
      return parsed;
    }
    return null;
  } catch {
    return null;
  }
}

/**
 * Deterministic suggestions builder — ranks the most actionable findings
 * from the structured analysis into 3-5 concrete tips. Used both as the
 * fallback when the LLM call fails/is unparseable, and as a sanity
 * reference the LLM path never needs but this keeps the two code paths
 * symmetric with buildDeterministicNarrative below.
 */
function buildDeterministicSuggestions(input: NarrativeInput): string[] {
  const suggestions: string[] = [];

  if (input.comparison?.biggestLossZone) {
    const z = input.comparison.biggestLossZone;
    suggestions.push(
      `Focus here first: ${z.lostSeconds.toFixed(2)}s lost between ${z.startDist.toFixed(0)}m and ${z.endDist.toFixed(0)}m vs lap ${input.referenceLapNum}.`
    );
  }

  const brakedCorners = input.corners.filter((c) => c.brakeDurationMeters > 0);
  if (brakedCorners.length > 0) {
    const worstTrail = brakedCorners.reduce((a, b) => (a.trailBrakePercent < b.trailBrakePercent ? a : b));
    if (worstTrail.trailBrakePercent < 0.3) {
      suggestions.push(
        `Corner ${worstTrail.id + 1}: only ${(worstTrail.trailBrakePercent * 100).toFixed(0)}% trail brake — carry a bit more brake into the turn to rotate the car earlier.`
      );
    }
  }

  if (input.corners.length > 0) {
    const roughest = input.corners.reduce((a, b) => (a.applicationSmoothness < b.applicationSmoothness ? a : b));
    if (roughest.applicationSmoothness < 0.5) {
      suggestions.push(
        `Corner ${roughest.id + 1}: throttle application is inconsistent on exit — smooth the initial squeeze before going to full throttle.`
      );
    }

    const latestThrottle = input.corners.reduce((a, b) => (a.distFromApexToThrottle > b.distFromApexToThrottle ? a : b));
    if (latestThrottle.distFromApexToThrottle > 20) {
      suggestions.push(
        `Corner ${latestThrottle.id + 1}: throttle came on ${latestThrottle.distFromApexToThrottle.toFixed(0)}m after the apex — there may be time available getting back to power sooner.`
      );
    }
  }

  const majorIssues = input.generalIssues.filter((i) => i.severity === 'major');
  if (majorIssues.length > 0) {
    const kinds = new Set(majorIssues.map((i) => i.kind));
    if (kinds.has('lockup')) {
      suggestions.push(`Lockup events detected this lap — ease initial brake pressure to avoid flat-spotting the tyres.`);
    }
    if (kinds.has('snap_correction')) {
      suggestions.push(`The rear stepped out at least once — consider slightly less aggressive turn-in or throttle mid-corner.`);
    }
    if (kinds.has('engine_over_rev')) {
      suggestions.push(`At least one missed upshift this lap — check your shift points, you're bouncing off the limiter.`);
    }
  }

  return suggestions.slice(0, 5);
}

/**
 * Deterministic fallback narrative — used when the LLM call fails, times
 * out, or returns something we can't parse. Template-built from the same
 * structured input the LLM would have received, so the UI always gets a
 * usable summary, per-corner notes, and suggestions even if the PitBoss
 * worker is down.
 */
function buildDeterministicNarrative(input: NarrativeInput): CoachingNarrative {
  const summaryParts: string[] = [];
  summaryParts.push(`Lap ${input.lapNum}: ${input.lapTime.toFixed(3)}s${input.lapValid ? '' : ' (invalid)'}.`);
  if (input.comparison) {
    const sign = input.comparison.totalDeltaSeconds >= 0 ? '+' : '';
    summaryParts.push(`${sign}${input.comparison.totalDeltaSeconds.toFixed(3)}s vs lap ${input.referenceLapNum}.`);
    if (input.comparison.biggestLossZone) {
      summaryParts.push(
        `Biggest loss: ${input.comparison.biggestLossZone.lostSeconds.toFixed(2)}s between ${input.comparison.biggestLossZone.startDist.toFixed(0)}m–${input.comparison.biggestLossZone.endDist.toFixed(0)}m.`
      );
    }
  }
  const majorIssueCount = input.generalIssues.filter((i) => i.severity === 'major').length;
  if (majorIssueCount > 0) {
    summaryParts.push(`${majorIssueCount} major issue(s) detected this lap.`);
  }

  const cornerNotes = new Map<number, string>();
  for (const c of input.corners) {
    const parts: string[] = [];
    parts.push(`Braked at ${c.brakePointDist.toFixed(0)}m, peak ${(c.brakePeakPressure * 100).toFixed(0)}% brake pressure, min speed ${c.minSpeedInCorner.toFixed(0)} km/h.`);
    parts.push(`Trail-braked through ${(c.trailBrakePercent * 100).toFixed(0)}% of the braking zone.`);
    parts.push(
      c.fullThrottleDist != null
        ? `Throttle applied ${c.distFromApexToThrottle.toFixed(0)}m after apex, full throttle by ${c.fullThrottleDist.toFixed(0)}m.`
        : `Throttle applied ${c.distFromApexToThrottle.toFixed(0)}m after apex; full throttle not reached before the next braking zone.`
    );
    if (c.issues.length > 0) {
      parts.push(`${c.issues.length} issue(s) flagged in this corner.`);
    }
    cornerNotes.set(c.id, parts.join(' '));
  }

  return {
    summaryText: summaryParts.join(' '),
    cornerNotes,
    suggestions: buildDeterministicSuggestions(input),
    source: 'deterministic',
  };
}

async function generateCoachingNarrative(input: NarrativeInput): Promise<CoachingNarrative> {
  try {
    const result = await pbInfer({
      mode: 'reasoning',
      system: COACH_SYSTEM_PROMPT,
      prompt: JSON.stringify(input),
      max_tokens: 1500,
      temperature: 0.4,
    });

    const parsed = parseNarrativeResponse(result.response);
    if (parsed) {
      const cornerNotes = new Map<number, string>();
      for (const [key, note] of Object.entries(parsed.cornerNotes)) {
        const id = Number(key);
        if (Number.isFinite(id) && typeof note === 'string') cornerNotes.set(id, note);
      }
      return { summaryText: parsed.summary, cornerNotes, suggestions: parsed.suggestions, source: 'llm' };
    }

    console.error('[telemetry-coach] pbInfer returned unparseable narrative JSON, falling back to deterministic:', result.response);
  } catch (err) {
    console.error('[telemetry-coach] pbInfer call failed, falling back to deterministic narrative:', err);
  }
  return buildDeterministicNarrative(input);
}

// =======================================================================
// 7. Top-level orchestrator
// =======================================================================

export async function buildCoachingReport(
  session: TelemetrySession,
  lapNum: number,
  referenceLapNum?: number
): Promise<CoachingReport> {
  const lap = session.laps.find((l) => l.lapNum === lapNum);
  if (!lap) throw new Error(`Lap ${lapNum} not found in session ${session.sessionUid}`);

  const referenceLap = referenceLapNum != null ? session.laps.find((l) => l.lapNum === referenceLapNum) : undefined;
  const comparison = referenceLap ? compareLaps(referenceLap, lap) : null;

  const corners = detectCorners(lap.frames);
  const cornerAnalysis = corners.map((corner, idx) => {
    const braking = analyzeBraking(lap.frames, corner);
    const throttle = analyzeThrottle(lap.frames, corner, corners[idx + 1] ?? null);
    const cornerIssues = detectIssues(framesInRange(lap.frames, corner.entryDist - 50, corner.exitDist + 50));
    return { corner, braking, throttle, issues: cornerIssues };
  });

  const allIssues = detectIssues(lap.frames);

  const narrativeInput: NarrativeInput = {
    lapNum: lap.lapNum,
    lapTime: lap.lapTime,
    lapValid: lap.lapValid,
    referenceLapNum: referenceLapNum ?? null,
    comparison: comparison
      ? {
          totalDeltaSeconds: comparison.totalDeltaSeconds,
          sectorDeltas: comparison.sectorDeltas,
          biggestGainZone: comparison.biggestGainZone,
          biggestLossZone: comparison.biggestLossZone,
        }
      : null,
    corners: cornerAnalysis.map(({ corner, braking, throttle, issues }) => ({
      id: corner.id,
      direction: corner.direction,
      entryDist: corner.entryDist,
      apexDist: corner.apexDist,
      exitDist: corner.exitDist,
      brakePointDist: braking.brakePointDist,
      brakePeakPressure: braking.brakePeakPressure,
      brakeDurationMeters: braking.brakeDurationMeters,
      trailBrakePercent: braking.trailBrakePercent,
      minSpeedInCorner: braking.minSpeedInCorner,
      throttleApplicationDist: throttle.throttleApplicationDist,
      distFromApexToThrottle: throttle.distFromApexToThrottle,
      fullThrottleDist: throttle.fullThrottleDist,
      applicationSmoothness: throttle.applicationSmoothness,
      issues,
    })),
    generalIssues: allIssues,
  };

  const narrative = await generateCoachingNarrative(narrativeInput);

  // Only computed if the LLM (or its fallback) left a gap — e.g. the model
  // omitted a corner from cornerNotes despite being given all of them.
  let deterministicFallback: CoachingNarrative | null = null;
  const fallbackNoteFor = (cornerId: number): string => {
    if (!deterministicFallback) deterministicFallback = buildDeterministicNarrative(narrativeInput);
    return deterministicFallback.cornerNotes.get(cornerId) ?? '';
  };

  const corners_: CornerCoaching[] = cornerAnalysis.map(({ corner, braking, throttle, issues }) => ({
    corner,
    braking,
    throttle,
    issues,
    coachingNote: narrative.cornerNotes.get(corner.id) ?? fallbackNoteFor(corner.id),
  }));

  return {
    lapNum,
    referenceLapNum: referenceLapNum ?? null,
    comparison,
    corners: corners_,
    issues: allIssues,
    summaryText: narrative.summaryText,
    suggestions: narrative.suggestions,
    narrativeSource: narrative.source,
  };
}
