// Pure types for the telemetry coaching engine — shared by the server-only
// analysis code (telemetry-coach.ts) and client components that render a
// CoachingReport (e.g. CoachingPanel.tsx). This file must never import
// pitboss-llm or anything from telemetry.ts/supabase/server — that's what
// breaks the client bundle. See the header comment in telemetry-coach.ts
// for the incident this pattern is guarding against.
//
// IMPORTANT: this file only DEFINES these types — it must never import or
// re-export them from itself or from telemetry-coach.ts. telemetry-coach.ts
// re-exports FROM this file (for backward-compatible server-side imports),
// not the other way around. A re-export block in this file pointing back
// at '@/lib/pitboss/telemetry-coach-types' is a circular self-import and
// will fail to compile ("Circular definition of import alias").

export interface DeltaPoint {
  dist: number;
  deltaSeconds: number; // positive = lapB slower than lapA at this point
}

export interface LapComparison {
  lapA: number; // lap number
  lapB: number;
  deltaCurve: DeltaPoint[]; // resampled onto a common distance grid
  totalDeltaSeconds: number; // + means lapB slower overall
  sectorDeltas: { sector1: number; sector2: number; sector3: number };
  biggestGainZone: { startDist: number; endDist: number; gainedSeconds: number } | null;
  biggestLossZone: { startDist: number; endDist: number; lostSeconds: number } | null;
}

export interface CornerSegment {
  id: number;
  entryDist: number;
  apexDist: number;
  exitDist: number;
  direction: 'left' | 'right';
}

export interface BrakingAnalysis {
  cornerId: number;
  brakePointDist: number; // distance where brake first exceeds threshold
  brakePeakPressure: number; // 0-1
  brakeDurationMeters: number;
  trailBrakePercent: number; // % of braking zone where steer + brake overlap
  minSpeedInCorner: number;
}

export interface ThrottleAnalysis {
  cornerId: number;
  throttleApplicationDist: number; // distance where throttle first exceeds threshold, post-apex
  distFromApexToThrottle: number;
  fullThrottleDist: number | null; // distance where throttle first reaches ~100%, null if not reached before next brake zone
  applicationSmoothness: number; // 0-1, higher = smoother ramp (lower variance in throttle derivative)
}

export type IssueKind = 'lockup' | 'snap_correction' | 'off_track_suspected' | 'engine_over_rev';

export interface DetectedIssue {
  kind: IssueKind;
  dist: number;
  severity: 'minor' | 'major';
  note: string;
}

export interface CornerCoaching {
  corner: CornerSegment;
  braking: BrakingAnalysis;
  throttle: ThrottleAnalysis;
  issues: DetectedIssue[];
  /**
   * Coaching prose for this corner — generated by the LLM, or a
   * deterministic template fallback if the LLM call failed. Never blank.
   */
  coachingNote: string;
}

export interface CoachingReport {
  lapNum: number;
  referenceLapNum: number | null;
  comparison: LapComparison | null;
  corners: CornerCoaching[];
  issues: DetectedIssue[]; // issues not tied to a specific corner
  summaryText: string;
  /**
   * 3-5 ranked, concrete next-lap tips — e.g. "carry more trail brake into
   * corner 4" or "focus on the 200-350m loss zone". Always grounded in the
   * corner/comparison/issue data above; never blank (falls back to a
   * deterministic template if the LLM call fails or is unparseable, same
   * as summaryText/coachingNote).
   */
  suggestions: string[];
  /** Whether summaryText / coachingNotes / suggestions came from the LLM or the deterministic fallback. */
  narrativeSource: 'llm' | 'deterministic';
}
